server:
  port: 8000
spring:
  application:
    name: currency-exchange

  datasource:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/projectdb?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true    
  service-url:
    defaultzone: http://localhost:8761/eureka
    
resilience4j:
  retry:
    instances:
      sample-api:
        maxRetryAttempts: 5
        waitDuration: 1s
        enableExponentialBackoff: true
  circuitbreaker:
    instances:
      default:
        failureRateThreshold: 90
  
  ratelimiter:
    instances:
      default:
        limitForPeriod: 2
        limitRefreshPeriod: 10s
  

